### PR TITLE
Fix for fake keypress bypass

### PR DESCRIPTION
**Pull request by Sc00bz**
I'm pretty sure this fixes this (https://twitter.com/securifybv/status/594189441633296385) but I still haven't figured out how to test edits for an extension.

### CODE REVIEW

**Comment by adhintz** [comment]
Thanks! I should add a section in chrome/README.md on how to compile and then locally run the extension.

Is this the bypass that results in sender.tab being undefined? http://pastebin.com/Bx0RsuSu

**Comment by adhintz** [comment]
I also have a commit that discards keyboardEvents with a charcode of 0, which should help. There's a 7-year-old bug (?) that sets the charcode to 0 for programmatically generated keyboardEvents: https://www.google.com/url?sa=D&q=https%3A%2F%2Fbugs.webkit.org%2Fshow_bug.cgi%3Fid%3D16735

**Comment by Sc00bz** [comment]
Just found out how key presses are failing. charCode is always zero.

> Is this the bypass that results in sender.tab being undefined?
Nope, I thought it was but sender.tab is defined.

> I also have a commit that discards keyboardEvents with a charcode of 0, which should help. There's a 7-year-old bug (?) that sets the charcode to 0 for programmatically generated keyboardEvents: https://bugs.webkit.org/show_bug.cgi?id=16735
Yeap that's why. So if that ever gets fixed then this will be broken.

**Comment by Sc00bz** [comment]
OK I quadruple checked this. It should work now. I'm sorry about submitting a pull request that was untested.

**Comment by adhintz** [comment]
No worries about not testing it the first time around. I'm happy to get pull requests in any shape.

I just committed the code I wrote yesterday. I went ahead and ignored charcode == 0 values early on: https://github.com/google/password-alert/blob/master/chrome/content_script.js#L528

**Comment by Sc00bz** [comment]
Yeah that's way better.

**Pull request closed without merging**
