### PR TITLE
Refactoring do.sh for building extension from source

### LINKED ISSUE #93: Building the Extension
Following instructions to build the extension from source results in a couple of errors. 

1. ERROR - Duplicate input: lib/closure-library/closure/goog/deps.js
2. background_compiled.js has an Uncaught ReferenceError: require is not defined.

### PR DESCRIPTION
**Pull request by eewayhsu**
1) Remove duplicate input called from compile.flags.
2) Fix SRC_DIRS to point to lib/closure-library/closure/goog from lib/closure-library

fixes #93

### CODE REVIEW

**Comment by eewayhsu** [comment]
I signed it!

**Comment by eewayhsu** [comment]
I signed it!

**Comment by eewayhsu** [comment]
Currently extension builds and runs, but throws `Unchecked runtime.lastError while running tabs.executeScript: The extensions gallery cannot be scripted.`.  There is a call to executeScript in background.js.

**Comment by adhintz** [comment]
Thanks for the fix!

**Pull request merged**
